import type { Database } from '@huddle/types';
import { isHuddleError } from './errors';
import { throwMapped, requireUserId, type HuddleClient } from './internal';

/**
 * Raw invite data functions, framework-free (same split as ./groups:
 * server code imports THIS module; hooks live in ./invites-hooks).
 *
 * Creation/listing/revocation are plain RLS-protected table operations
 * (admins only). Peek + accept go through SECURITY DEFINER RPCs because
 * the acceptor isn't a member yet (D48).
 */

type GroupRow = Database['public']['Tables']['groups']['Row'];
export type GroupInviteRow = Database['public']['Tables']['group_invites']['Row'];
export type InvitePeek =
  Database['public']['Functions']['peek_invite']['Returns'][number];

// -----------------------------------------------------------------------
// Invite-flow error contract (HD### SQLSTATEs raised by the RPCs)
// -----------------------------------------------------------------------

export type InviteErrorKind =
  | 'not_found'
  | 'expired'
  | 'already_used'
  | 'wrong_user'
  | 'already_member';

const INVITE_ERROR_CODES: Record<string, InviteErrorKind> = {
  HD000: 'not_found',
  HD001: 'expired',
  HD002: 'already_used',
  HD003: 'wrong_user',
  HD004: 'already_member',
};

/** Classify an error from acceptInvite/peekInvite, or null if unrelated. */
export function inviteErrorKind(e: unknown): InviteErrorKind | null {
  if (!isHuddleError(e)) return null;
  const code = e.huddle.code;
  return code ? (INVITE_ERROR_CODES[code] ?? null) : null;
}

// -----------------------------------------------------------------------
// Query key factory
// -----------------------------------------------------------------------

export const inviteQueryKeys = {
  forGroup: (groupId: string) => ['groups', groupId, 'invites'] as const,
  peek: (token: string) => ['invites', 'peek', token] as const,
};

// -----------------------------------------------------------------------
// Admin-side operations (plain RLS-protected table access)
// -----------------------------------------------------------------------

export interface CreateInviteParams {
  groupId: string;
  invitedEmail?: string;
  invitedUserId?: string;
}

/**
 * Create an invite. RLS restricts this to group admins. The token is
 * generated by the DB column default and comes back in the returned row;
 * RETURNING is safe here because the creating admin already passes the
 * SELECT policy (unlike create_group — see D45/D48).
 */
export async function createInvite(
  client: HuddleClient,
  params: CreateInviteParams,
): Promise<GroupInviteRow> {
  const userId = await requireUserId(client);

  const { data, error } = await client
    .from('group_invites')
    .insert({
      group_id: params.groupId,
      invited_email: params.invitedEmail ?? null,
      invited_user_id: params.invitedUserId ?? null,
      created_by: userId,
    })
    .select()
    .single();

  if (error) throwMapped(error);
  return data!;
}

/** List open (unaccepted) invites for a group. Admins only via RLS. */
export async function fetchGroupInvites(
  client: HuddleClient,
  groupId: string,
): Promise<GroupInviteRow[]> {
  const { data, error } = await client
    .from('group_invites')
    .select('*')
    .eq('group_id', groupId)
    .is('accepted_at', null)
    .order('created_at', { ascending: false });

  if (error) throwMapped(error);
  return data ?? [];
}

/** Revoke (delete) an open invite. Admins only via RLS. */
export async function revokeInvite(
  client: HuddleClient,
  inviteId: string,
): Promise<void> {
  const { error } = await client.from('group_invites').delete().eq('id', inviteId);
  if (error) throwMapped(error);
}

// -----------------------------------------------------------------------
// Acceptor-side operations (SECURITY DEFINER RPCs)
// -----------------------------------------------------------------------

/**
 * Look up what a token is for before accepting. Returns group name,
 * inviter display name, expiry, and a computed status:
 * 'valid' | 'expired' | 'accepted' | 'already_member' | 'wrong_user'.
 */
export async function peekInvite(
  client: HuddleClient,
  token: string,
): Promise<InvitePeek> {
  const { data, error } = await client
    .rpc('peek_invite', { p_token: token })
    .single();

  if (error) throwMapped(error);
  return data!;
}

/** Accept an invite. Returns the joined group on success. */
export async function acceptInvite(
  client: HuddleClient,
  token: string,
): Promise<GroupRow> {
  const { data, error } = await client.rpc('accept_invite', { p_token: token });

  if (error) throwMapped(error);
  return data!;
}
